modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="hostilenetworks"
type="required"
versionRange="[6.5.1,7)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="neovitae"
type="required"
versionRange="[1.1.19,1.2)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="placebo"
type="required"
versionRange="[9.9.0,10)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="extrahnn"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
