package com.leo.sanguine_networks.client;

// Generated by scripts/import_hnn_assets.py from textures/block/color_stripes.png.
public final class SnnPalette {
    private SnnPalette() {}
    public static final int PRIMARY = 0xFFFF0000;
    public static final int HIGHLIGHT = 0xFFFF6161;
    public static final int SHADOW = 0xFF241212;
    public static final int ERROR = 0xFFC64747;
}
