#!/usr/bin/env python3
"""Extract pinned HNN artwork and remap its accent ramp using SNN color_stripes.png.

Requires Pillow. Optional argument: path to the HNN 5.3.3 dependency JAR.
Geometry, UVs, neutral/red pixels, alpha and animation metadata remain unchanged.
"""
import colorsys
import io
import json
from pathlib import Path
import sys
import zipfile

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "src/main/resources/assets/sanguine_networks"
if len(sys.argv) > 1:
    JAR = Path(sys.argv[1])
else:
    JAR = next((Path.home() / ".gradle/caches/modules-2/files-2.1/curse.maven/hostile-neural-networks-552574/5895036").glob("*/*.jar"))
PREFIX = "assets/hostilenetworks/"
with zipfile.ZipFile(JAR) as archive:
    original = Image.open(io.BytesIO(archive.read(PREFIX + "textures/block/color_stripes.png"))).convert("RGBA")
    target = Image.open(ASSETS / "textures/block/color_stripes.png").convert("RGBA")
    assert original.size == target.size
    ramp = dict(zip(original.get_flattened_data(), target.get_flattened_data()))
    accent = target.getpixel((0, 0))
    hue = colorsys.rgb_to_hsv(*(c / 255 for c in accent[:3]))[0]

    def remap(pixel):
        if pixel in ramp:
            return ramp[pixel]
        r, g, b, a = pixel
        if not a or not (g > r and b > r):
            return pixel
        _, saturation, value = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
        return (*[round(c * 255) for c in colorsys.hsv_to_rgb(hue, saturation, value)], a)

    # Preserve all original Virtual Sacrificer block and machine GUI artwork.
    texture_names = {
        "gui/default_gui": "gui/player_inventory",
        "jei/sim_chamber": "jei/virtual_sacrificer",
    }
    textures = set(texture_names)
    for texture in sorted(textures):
        name = "textures/" + texture + ".png"
        source = Image.open(io.BytesIO(archive.read(PREFIX + name))).convert("RGBA")
        recolored = source.copy()
        recolored.putdata([remap(pixel) for pixel in source.get_flattened_data()])
        output = ASSETS / ("textures/" + texture_names[texture] + ".png")
        output.parent.mkdir(parents=True, exist_ok=True)
        recolored.save(output)
        assert recolored.size == source.size
        for before, after in zip(source.get_flattened_data(), recolored.get_flattened_data()):
            assert before[3] == after[3]
            if before[0] == before[1] == before[2] or before[0] >= max(before[1], before[2]):
                assert before == after, (texture, before, after)
        metadata = PREFIX + name + ".mcmeta"
        if metadata in archive.namelist():
            Path(str(output) + ".mcmeta").write_bytes(archive.read(metadata))
        print(output.relative_to(ASSETS))

    java = ROOT / "src/main/java/com/leo/sanguine_networks/client/SnnPalette.java"
    java.write_text("""package com.leo.sanguine_networks.client;

// Generated by scripts/import_hnn_assets.py from textures/block/color_stripes.png.
public final class SnnPalette {
    private SnnPalette() {}
""" + "".join(f"    public static final int {name} = 0x{(a << 24 | r << 16 | g << 8 | b):08X};\n"
              for name, (r, g, b, a) in [(name, target.getpixel((index, 0)))
                for name, index in [("PRIMARY", 0), ("HIGHLIGHT", 1), ("SHADOW", 2), ("ERROR", 4)]]) + "}\n")
print("Verified dimensions, alpha, neutral/red pixels, and preserved animation metadata.")
